[build.environment]
  NPM_FLAGS = "--version"
[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "1; mode=block"
    X-DNS-Prefetch-Control = "on"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy: "camera=(), microphone=(), geolocation=()"
